### PR TITLE
[WIP] Add harvester for Addis Ababa University

### LINKED ISSUE #318: Add harvester for Addis Ababa University
homepage: http://etd.aau.edu.et/dspace/

OAI - http://etd.aau.edu.et/dspace-oai/request?verb=Identify

### PR DESCRIPTION
**Pull request by erinspace**
Closes #318

Note: Not ready for merge into prod, pending conversation with repository about broken identifiers in the source metadata.

### CODE REVIEW

**Comment by fabianvf** [comment]
status?

**Comment by erinspace** [comment]
Harvester source still seems to be down....

**Comment by kms6bn** [comment]
This can be closed, my code adding Addis Ababa has been merged.

**Comment by erinspace** [comment]
Sweet, thanks @kms6bn !

**Pull request closed without merging**
